import type { Metadata } from 'next'
// import { Inter } from 'next/font/google'

import { ThemeProvider } from "@/utils/context/theme";

import './globals.css'
import Header from '@/components/Header/Header'
import Footer from '@/components/Footer.tsx/Footer'
import { Toaster } from 'sonner';

// const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'BlaX, achetez en un clic et en toute sécurité',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <ThemeProvider>
      <html lang="fr">
        <body className='bodyLayout'>
          <Header />
          <main className='main'>
            {children}
          </main>
          <Footer />
          <Toaster
            toastOptions={
              {
                style: {
                  backgroundColor: '#25273c',
                  border: 'none',
                  fontSize: '1em'
                }
              }
            }
            position="bottom-center"
          />
        </body>
      </html>
    </ThemeProvider>
  )
}
